# Default values for mediawiki.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: thghtwrksreg134.azurecr.io/mediawiki
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.39.3

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

strategy:
  type: RollingUpdate

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: nginx
  pathType: Prefix
